version: '3.8'

# Services
services:
  # Server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3000:3000"
 
  # Client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile

    container_name: client
    ports:
      - "8080:80"
    depends_on:
      - server