name: "[1]Infra - Deploy"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["terraform/**"]

jobs:
  deployinfra:
    name: Terraform Deploy
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Initialise project and deploy terraform
        run: |
          cd terraform
          terraform fmt
          terraform init -lock=false
          terraform apply  -lock=false --auto-approve=true
      
      - name: Output EC2 instance public IP to file
        run: |
          cd terraform
          touch ec2_ip.txt
          echo "$(terraform output -raw ec2_instance_public_ip)" > ec2_ip.txt
      
      - name: Upload EC2 instance public IP to S3
        run: |
          cd terraform
          aws s3 cp ec2_ip.txt s3://hhavr-terraform-state/aux/ec2_ip.txt
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1