name: Infra - Destroy

on:
  workflow_dispatch:

jobs:
  destroyinfra:
    name: Terraform Destroy
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Initialise project and deploy terraform
        run: |
          cd terraform
          terraform fmt
          terraform init -lock=false
          terraform apply  -destroy -target aws_lb_listener.listener -target aws_ecs_service.app_service -target aws_lb_target_group.target_group -target aws_security_group.load_balancer_security_group -target aws_default_subnet.default_subnet_a -target aws_default_subnet.default_subnet_b -target aws_alb.application_load_balancer -target aws_ecs_cluster.my_cluster -target aws_default_vpc.default_vpc -target aws_ecs_task_definition.app_task -lock=false --auto-approve=true

