name: Infra - Destroy

on:
  workflow_dispatch:

jobs:
  destroyinfra:
    name: Terraform Destroy
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Initialise project and deploy terraform
        run: |
          cd terraform
          terraform fmt
          terraform init -lock=false
          terraform apply  -destroy -target aws_vpc_security_group_ingress_rule.allow_https -target aws_vpc_security_group_ingress_rule.allow_https -target aws_vpc_security_group_ingress_rule.allow_ssh -target aws_instance.hh_ec2 -target aws_ec2_instance_state.test -lock=false --auto-approve=true

